name: PR Work Item Link and Title Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pr_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        
      - name: Check PR title and work item link
        run: |
          pr_number=${{ github.event.pull_request.number }}
          pr_title=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number" | jq -r '.title')
          
          if [[ "$pr_title" == null ]]; then
            echo "Failed to retrieve PR title"
            exit 1
          fi
          
          if [[ ! "$pr_title" =~ ^AB: ]]; then
            echo "PR title does not start with 'AB:'"
            exit 1
          fi
