name: Workflow Example

on:
  push:
    branches:
      - main

jobs:
  extract_id_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract id value
        run: |
          id_value=$(awk '/^[[:blank:]]*id:/ { print $2 }' asset.yml)
          echo "id: $id_value"

  other_job:
    needs: extract_id_job
    runs-on: ubuntu-latest

    steps:
      - name: Read id value from file
        run: |
          id_value=$(cat id_value.yml)
          echo "ID value is: $id_value"

      # Continue with other steps using the id_value variable
