name: Glapi Workflow

on:
  push:
    branches:
      - main

jobs:
  check_id_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read asset.yml file
        run: echo "::set-output name=id_value::$(awk '/^[[:blank:]]*id:/ { print $2 }' asset.yml)" >> $GITHUB_ENV

  glapi_job:
    runs-on: ubuntu-latest
    needs: check_id_job

    steps:
      - name: Run Glapi
        if: ${{ steps.read_asset.outputs.id_value != 'APPSVC0000' }}
        run: |
          echo "Running the Glapi job..."
          # Your Glapi job execution code here
