name: Workflow Example

on:
  push:
    branches:
      - main
      
jobs:
  first_job:
    runs-on: ubuntu-latest

    outputs:
      idoutput: ${{ steps.GetID.outputs.idoutput }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: GetID
        run: |
          id_value=$(awk '/^[[:blank:]]*id:/ { print $2 }' asset.yml)
          echo $id_value
          conditn=
          echo "::set-output name=idoutput::$id_value"
  second_job:
    needs: [first_job]
    runs-on: ubuntu-latest
    if: needs.first_job.outputs.idoutput != 'APPSVC00000'
    steps:
      - run: |
          echo "ID Output: ${{ needs.first_job.outputs.idoutput }} "
          echo "Condition: ${{ needs.first_job.outputs.idoutput != 'APPSVC00000' }}"
