name: Workflow Example

on:
  push:
    branches:
      - main

# jobs:
#   extract_id_job:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Extract id value
#         run: |
#           id_value=$(awk '/^[[:blank:]]*id:/ { print $2 }' asset.yml)
#           echo "id_value=$id_value" >> $GITHUB_ENV
#       - name: list
#         if: ${{ env.id_value != 'APPSVC00000'}} 
#         run: echo "running the step"
#       # Continue with other steps using the id_value variable
jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.getid.outputs.id_value }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        id: getid
        run: |
          id_value=$(awk '/^[[:blank:]]*id:/ { print $2 }' asset.yml)
          echo $id_value
        # echo "id_value=$id_value" >> $GITHUB_OUTPUT
          echo "::set-output name=id::$id_value"
  second_job:
    needs: [first_job]
    runs-on: ubuntu-latest
    if: needs.first_job.outputs.id != 'APPSVC00000'
    steps:
      - run: |
          echo "$id"
