name: Workflow Example

on:
  push:
    branches:
      - main

jobs:
  extract_id_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract id value
        id: extract_id
        run: |
          awk '/^[[:blank:]]*id:/ { print $2 }' asset.yml

  other_job:
    needs: extract_id_job
    runs-on: ubuntu-latest

    steps:
      - name: Use id value in if statement
        run: |
          if [[ "${{ needs.extract_id_job.outputs.id_value }}" != "APPSVC0000" ]]; then
            echo "ID is not APPSVC0000. Run the job..."
            # Your job execution code here
          else
            echo "ID is APPSVC0000. Skip the job..."
          fi
